renaming test-harness gpu dockerfile

diff --git a/docker/Dockerfile.gpu b/docker/Dockerfile.gpu
--- a/docker/Dockerfile.gpu
+++ b/docker/Dockerfile.gpu
@@ -1,80 +1,149 @@
-# This file used on Docker Hub to automatically create offical images
-#FROM nvidia/cuda:10.1-devel-ubuntu16.04 AS builder
-FROM nvidia/cuda:10.1-runtime-ubuntu16.04 AS builder
+# build stage
+FROM nvidia/cuda:10.1-devel-ubuntu18.04 as builder
+ENV DEBIAN_FRONTEND noninteractive
+RUN export DEBIAN_FRONTEND=noninteractive
+RUN apt-get update && apt-get dist-upgrade -y && \
+    apt-get install software-properties-common -y && \
+    add-apt-repository ppa:longsleep/golang-backports && \
+    apt-get update && apt-get dist-upgrade -y && \
+    apt-get install -y build-essential pkg-config autoconf gnutls-dev \
+            git curl golang-go && \
+   ## curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb && \
+   # curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
+   # dpkg --force-confdef --force-confnew -i ./cuda-repo-ubuntu1804_10.1.243-1_amd64.deb && \
+    ## apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub && \
+   # apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub && \
+    apt-get update && \
+   # apt-get install cuda-10-1 -y && \
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+#RUN apt-get install -y libnvidia-encode-418   
+
+RUN git clone -b nasm-2.14.02 https://repo.or.cz/nasm.git "$HOME/nasm" && \
+    cd "$HOME/nasm" && \
+    ./autogen.sh && \
+    ./configure && \
+    make && \
+    make install || echo "Installing docs fails but should be OK otherwise"
+
+RUN git clone http://git.videolan.org/git/x264.git "$HOME/x264" && \
+    cd "$HOME/x264" && \
+    git checkout 545de2ffec6ae9a80738de1b2c8cf820249a2530 && \
+    ./configure --enable-pic --enable-static --disable-cli && \
+    make && \
+    make install-lib-static
+
+RUN git clone https://git.ffmpeg.org/ffmpeg.git "$HOME/ffmpeg"
+
+RUN git clone --single-branch https://github.com/FFmpeg/nv-codec-headers && \
+    cd nv-codec-headers && \
+    make install && \
+    cd .. && \
+    rm -rf nv-codec-headers
+
+RUN export PATH=/usr/local/cuda/bin:$PATH && \
+    cd "$HOME/ffmpeg" && \
+    git checkout 4cfc34d9a8bffe4a1dd53187a3e0f25f34023a09 && \
+    ./configure --disable-static --enable-shared \
+        --enable-gpl --enable-nonfree --enable-libx264 --enable-cuda --enable-cuvid \
+        --enable-nvenc --enable-cuda-nvcc --enable-libnpp --enable-gnutls \
+        --extra-ldflags=-L/usr/local/cuda/lib64 \
+        --extra-cflags='-pg -I/usr/local/cuda/include' --disable-stripping
+
+RUN export PATH=$HOME/compiled/bin:$PATH && \
+    export PATH=/usr/local/cuda/bin:$PATH && \
+    export PKG_CONFIG_PATH=$HOME/compiled/lib/pkgconfig && \
+    cd "$HOME/ffmpeg" && \
+    make && make install
+
+RUN export PATH=$HOME/compiled/bin:$PATH && \
+    export PATH=/usr/local/cuda/bin:$PATH && \
+    export PKG_CONFIG_PATH=$HOME/compiled/lib/pkgconfig && \
+    go get github.com/livepeer/go-livepeer/cmd/livepeer && \
+    cd "$HOME/go/src/github.com/livepeer/go-livepeer" && \
+    go build ./cmd/livepeer/livepeer.go && \
+    go build ./cmd/devtool/devtool.go
+
+ENV LD_LIBRARY_PATH /usr/local/lib/
+
+# final stage
+FROM nvidia/cuda:10.1-devel-ubuntu18.04
+ENV DEBIAN_FRONTEND noninteractive
+RUN export DEBIAN_FRONTEND=noninteractive
+RUN apt-get update && apt-get dist-upgrade -y && \
+    apt-get install software-properties-common -y && \
+    add-apt-repository ppa:longsleep/golang-backports && \
+    apt-get update && apt-get dist-upgrade -y && \
+    apt-get install -y build-essential pkg-config autoconf gnutls-dev \
+            git curl golang-go && \
+    ##apt-get install -y libnvidia-encode-430 && \
+    ##curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.0.130-1_amd64.deb && \
+    ##dpkg --force-confdef --force-confnew -i ./cuda-repo-ubuntu1804_10.0.130-1_amd64.deb && \
+    ##apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub && \
+    
+    apt-get update && \
+    #apt-get install cuda-10-1 -y && \
+    apt-get clean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+RUN add-apt-repository universe && apt-get update &&  apt-get install -y jq
+
+RUN curl -O http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/cuda-repo-ubuntu1604_10.1.168-1_amd64.deb && \
+    dpkg --force-confdef --force-confnew -i ./cuda-repo-ubuntu1604_10.1.168-1_amd64.deb && \
+    apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub && \
+   
+    curl -O http://ftp.ubuntu.com/ubuntu/ubuntu/pool/restricted/n/nvidia-graphics-drivers-418/libnvidia-compute-418_418.56-0ubuntu1_amd64.deb && \
+    dpkg --force-confdef --force-confnew -i ./libnvidia-compute-418_418.56-0ubuntu1_amd64.deb && \
+
+    curl -O http://ftp.ubuntu.com/ubuntu/ubuntu/pool/restricted/n/nvidia-graphics-drivers-418/libnvidia-decode-418_418.56-0ubuntu1_amd64.deb && \
+    dpkg --force-confdef --force-confnew -i ./libnvidia-decode-418_418.56-0ubuntu1_amd64.deb && \
+
+    curl -O http://ftp.ubuntu.com/ubuntu/ubuntu/pool/restricted/n/nvidia-graphics-drivers-418/libnvidia-encode-418_418.56-0ubuntu1_amd64.deb && \
+    dpkg --force-confdef --force-confnew -i ./libnvidia-encode-418_418.56-0ubuntu1_amd64.deb
+
+# everything above this line has already been cached in the build stage -
+# we save time and disk space by keeping the common parts of each stage
+# identical at the start of each image build
+
+COPY --from=builder /usr/local/lib/* /usr/local/lib/
+COPY --from=builder /root/go/src/github.com/livepeer/go-livepeer/devtool /usr/local/bin/
+COPY --from=builder /root/go/src/github.com/livepeer/go-livepeer/livepeer /usr/local/bin/
+
+RUN ln -s /usr/local/bin/livepeer /
+RUN ln -s /usr/local/bin/livepeer /usr/bin/
+ENV LD_LIBRARY_PATH /usr/local/lib/
+
+# Keylase patch
+ENV NVIDIA_VISIBLE_DEVICES all
+ENV NVIDIA_DRIVER_CAPABILITIES compute,video,utility
+
+RUN mkdir -p /usr/local/bin /patched-lib
+COPY docker/patch.sh docker/gpu-start.sh /usr/local/bin/
+RUN chmod +x /usr/local/bin/patch.sh /usr/local/bin/gpu-start.sh
 
 
-ENV PATH "/usr/lib/go-1.12/bin:/go/bin:${PATH}"
-ENV PKG_CONFIG_PATH "/root/compiled/lib/pkgconfig"
-ENV CPATH /usr/local/cuda/include
-ENV LIBRARY_PATH /usr/local/cuda/lib64
-
-RUN apt-get update \
-  && apt-get install -y software-properties-common  curl \
-  && curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - \
-  && add-apt-repository ppa:longsleep/golang-backports -y \
-  && apt-get update \
-  && apt-get -y install build-essential pkg-config autoconf gnutls-dev golang-1.12-go sudo git python \
-  && add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs)  stable" \
-  && apt-get update \
-  && apt-get install docker-ce-cli
-
-
-ENV PKG_CONFIG_PATH /root/compiled/lib/pkgconfig
-ENV CPATH /usr/local/cuda/include
-ENV LIBRARY_PATH /usr/local/cuda/lib64
-ENV LD_LIBRARY_PAT /usr/local/cuda/lib64
-ENV GOPATH /go
-
-WORKDIR /go/src/github.com/livepeer/go-livepeer
-
-RUN go get github.com/golang/glog
-RUN go get -u -v github.com/livepeer/m3u8
-RUN go get github.com/aws/aws-sdk-go/aws
-RUN go get -u google.golang.org/grpc
-RUN go get github.com/pkg/errors
-RUN go get github.com/stretchr/testify/mock
-RUN go get -u -v go.opencensus.io/stats
-RUN go get -u -v go.opencensus.io/tag
-RUN go get -u -v contrib.go.opencensus.io/exporter/prometheus
-
-#ENV DEBIAN_FRONTEND noninteractive 
-#RUN apt-get -y install nvidia-418
-
-ADD ./install_ffmpeg.sh ./install_ffmpeg.sh
-RUN ./install_ffmpeg.sh
-
-ADD ./install_dependencies.sh ./install_dependencies.sh
-RUN ./install_dependencies.sh
-
-COPY . .
-RUN git describe --always --long --dirty > .git.describe
-
-RUN go get -v ./cmd/livepeer/...
-RUN go get -v ./cmd/livepeer_cli/...
-
-RUN go build -ldflags="-X github.com/livepeer/go-livepeer/core.LivepeerVersion=$(cat VERSION)-$(cat .git.describe)" -v cmd/livepeer/livepeer.go
-RUN go build -ldflags="-X github.com/livepeer/go-livepeer/core.LivepeerVersion=$(cat VERSION)-$(cat .git.describe)" -v cmd/livepeer_cli/*
-
-#FROM debian:stretch-slim
-
+#ENTRYPOINT [ "/root/go/bin/livepeer" ]
 WORKDIR /root
-RUN apt update && apt install -y  ca-certificates jq libgnutls30 && apt clean
+
+#RUN apt-get install -y libnvidia-encode-418   
+
 RUN mkdir -p /root/.lpData/mainnet/keystore && \
   mkdir -p /root/.lpData/rinkeby/keystore && \
   mkdir -p /root/.lpData/devenv/keystore && mkdir -p /root/.lpData/offchain/keystore
-RUN cp /go/src/github.com/livepeer/go-livepeer/livepeer /usr/bin/livepeer
-RUN cp /go/src/github.com/livepeer/go-livepeer/livepeer_cli /usr/bin/livepeer_cli
+#RUN cp /root/go/src/github.com/livepeer/go-livepeer/livepeer /usr/bin/livepeer
+#RUN cp /root/go/src/github.com/livepeer/go-livepeer/livepeer_cli /usr/bin/livepeer_cli
 
 #COPY --from=builder /go/src/github.com/livepeer/go-livepeer/livepeer /usr/bin/livepeer
 #COPY --from=builder /go/src/github.com/livepeer/go-livepeer/livepeer_cli /usr/bin/livepeer_cli
 
-COPY docker/start.sh .
-RUN chmod +x start.sh
+#COPY docker/start.sh .
+#RUN chmod +x start.sh
 
 EXPOSE 7935/tcp
 EXPOSE 8935/tcp
 EXPOSE 1935/tcp
 
-ENTRYPOINT ["/root/start.sh"]
+ENTRYPOINT ["/usr/local/bin/gpu-start.sh"]
 CMD ["--help"]
 
